import os
import django
from datetime import date, timedelta

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'cropcalendar_backend.settings')
django.setup()

from django.contrib.auth.models import User
from crops.models import Category, Crop, UserCropSchedule

def seed():
    print('Starting database seeding...')

    # Check if demo accounts should be created
    CREATE_DEMO_ACCOUNTS = os.getenv('CREATE_DEMO_ACCOUNTS', 'False').lower() in ('true', '1', 'yes')

    # 1. Create Users (only if demo accounts are enabled)
    if CREATE_DEMO_ACCOUNTS:
        admin_user, created = User.objects.get_or_create(
            username='admin',
            defaults={
                'email': 'admin@cropcalendar.com',
                'is_staff': True,
                'is_superuser': True,
            }
        )
        if created:
            admin_user.set_password('admin123')
            admin_user.save()
            print('Created admin user: admin / admin123')
        else:
            admin_user.set_password('admin123')
            admin_user.is_staff = True
            admin_user.is_superuser = True
            admin_user.save()
            print('Updated admin user')

        gardener_user, created = User.objects.get_or_create(
            username='gardener',
            defaults={
                'email': 'gardener@cropcalendar.com',
                'is_staff': False,
                'is_superuser': False,
            }
        )
        if created:
            gardener_user.set_password('user123')
            gardener_user.save()
            print('Created gardener user: gardener / user123')
        else:
            gardener_user.set_password('user123')
            gardener_user.save()
            print('Updated gardener user')
    else:
        print('Demo account creation skipped (CREATE_DEMO_ACCOUNTS is not set to true)')
        # Get references to existing admin/gardener users if they exist for later use
        try:
            admin_user = User.objects.get(username='admin')
        except User.DoesNotExist:
            admin_user = None
        try:
            gardener_user = User.objects.get(username='gardener')
        except User.DoesNotExist:
            gardener_user = None

    # 2. Categories
    categories_data = [
        {'name': 'Vegetables', 'slug': 'vegetables', 'icon': 'Carrot', 'description': 'Nutritious garden vegetables for kitchen cooking.'},
        {'name': 'Leafy Greens', 'slug': 'leafy-greens', 'icon': 'Salad', 'description': 'Fast-growing greens rich in vitamins and minerals.'},
        {'name': 'Fruits & Berries', 'slug': 'fruits-berries', 'icon': 'Apple', 'description': 'Sweet and sun-loving fresh produce.'},
        {'name': 'Root Vegetables', 'slug': 'root-vegetables', 'icon': 'Sprout', 'description': 'Underground treasures with extended storage life.'},
        {'name': 'Herbs & Aromatics', 'slug': 'herbs-aromatics', 'icon': 'Leaf', 'description': 'Flavorful herbs to elevate your culinary dishes.'},
        {'name': 'Legumes & Pods', 'slug': 'legumes-pods', 'icon': 'Wheat', 'description': 'Nitrogen-fixing plants providing protein-rich yields.'},
    ]

    cat_map = {}
    for cat_item in categories_data:
        c, _ = Category.objects.get_or_create(
            slug=cat_item['slug'],
            defaults=cat_item
        )
        cat_map[c.slug] = c

    # 3. Crops Data with growth days, images, and tips
    crops_data = [
        {
            'name': 'French Breakfast Radish',
            'scientific_name': 'Raphanus sativus',
            'category': cat_map['root-vegetables'],
            'growth_days': 24,
            'image_url': 'https://images.unsplash.com/photo-1593105544559-ecb03bf76f82?auto=format&fit=crop&w=800&q=80',
            'description': 'Crisp, peppery roots with white tips. One of the fastest growing vegetables in any garden.',
            'season': 'Spring',
            'difficulty': 'Easy',
            'sunlight': 'Full Sun',
            'watering': 'Moderate',
            'germination_days': 4,
            'spacing_cm': 8,
            'harvest_window_days': 7,
            'planting_tips': 'Sow every 2 weeks for continuous spring harvests. Keep soil evenly moist to avoid pithy roots.',
            'companion_plants': 'Carrots, Lettuce, Peas'
        },
        {
            'name': 'Baby Spinach',
            'scientific_name': 'Spinacia oleracea',
            'category': cat_map['leafy-greens'],
            'growth_days': 35,
            'image_url': 'https://images.unsplash.com/photo-1576045057995-568f588f82fb?auto=format&fit=crop&w=800&q=80',
            'description': 'Tender, nutrient-dense dark green leaves ideal for fresh salads, smoothies, and light sauteing.',
            'season': 'Autumn',
            'difficulty': 'Easy',
            'sunlight': 'Partial Shade',
            'watering': 'Moderate',
            'germination_days': 6,
            'spacing_cm': 15,
            'harvest_window_days': 14,
            'planting_tips': 'Harvest outer leaves as cut-and-come-again. Thrives in cool weather and tolerates mild frost.',
            'companion_plants': 'Strawberries, Onions, Peas'
        },
        {
            'name': 'Genovese Basil',
            'scientific_name': 'Ocimum basilicum',
            'category': cat_map['herbs-aromatics'],
            'growth_days': 40,
            'image_url': 'https://images.unsplash.com/photo-1618164435735-413d3b066c9a?auto=format&fit=crop&w=800&q=80',
            'description': 'Classic sweet Italian basil with glossy green leaves and fragrant perfume. Essential for pesto and pizza.',
            'season': 'Summer',
            'difficulty': 'Easy',
            'sunlight': 'Full Sun',
            'watering': 'Moderate',
            'germination_days': 7,
            'spacing_cm': 25,
            'harvest_window_days': 30,
            'planting_tips': 'Pinch off the top flower buds regularly to encourage bushier growth and prevent bitterness.',
            'companion_plants': 'Tomatoes, Peppers, Oregano'
        },
        {
            'name': 'Butterhead Lettuce',
            'scientific_name': 'Lactuca sativa var. capitata',
            'category': cat_map['leafy-greens'],
            'growth_days': 45,
            'image_url': 'https://images.unsplash.com/photo-1622206151226-18ca2c9ab4a1?auto=format&fit=crop&w=800&q=80',
            'description': 'Silky soft, buttery leaves forming loose, delicate rosettes with mild, sweet flavor.',
            'season': 'Spring',
            'difficulty': 'Easy',
            'sunlight': 'Partial Shade',
            'watering': 'Moderate',
            'germination_days': 7,
            'spacing_cm': 20,
            'harvest_window_days': 10,
            'planting_tips': 'Provide afternoon shade during hot spells to prevent bolting.',
            'companion_plants': 'Carrots, Radishes, Chives'
        },
        {
            'name': 'Sugar Snap Peas',
            'scientific_name': 'Pisum sativum var. macrocarpon',
            'category': cat_map['legumes-pods'],
            'growth_days': 58,
            'image_url': 'https://images.unsplash.com/photo-1589927986089-35812388d1f4?auto=format&fit=crop&w=800&q=80',
            'description': 'Plump, juicy, crunchy edible pods that can be eaten raw right off the vine or stir-fried.',
            'season': 'Spring',
            'difficulty': 'Easy',
            'sunlight': 'Full Sun',
            'watering': 'Moderate',
            'germination_days': 8,
            'spacing_cm': 10,
            'harvest_window_days': 21,
            'planting_tips': 'Provide a trellis or wire fence for climbing vines up to 5 feet high.',
            'companion_plants': 'Carrots, Cucumbers, Corn'
        },
        {
            'name': 'English Cucumber',
            'scientific_name': 'Cucumis sativus',
            'category': cat_map['vegetables'],
            'growth_days': 60,
            'image_url': 'https://images.unsplash.com/photo-1449300079323-02e209d9d3a6?auto=format&fit=crop&w=800&q=80',
            'description': 'Crisp, refreshing cucumbers with thin skin and almost no seeds. Perfect for summer salads.',
            'season': 'Summer',
            'difficulty': 'Intermediate',
            'sunlight': 'Full Sun',
            'watering': 'High',
            'germination_days': 6,
            'spacing_cm': 45,
            'harvest_window_days': 30,
            'planting_tips': 'Trellising keeps the fruits straight and reduces mildew risk by ensuring good air flow.',
            'companion_plants': 'Beans, Corn, Radishes, Sunflowers'
        },
        {
            'name': 'Sweet Rainbow Carrots',
            'scientific_name': 'Daucus carota subsp. sativus',
            'category': cat_map['root-vegetables'],
            'growth_days': 72,
            'image_url': 'https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?auto=format&fit=crop&w=800&q=80',
            'description': 'Vibrant medley of purple, yellow, and deep orange sweet roots packed with beta-carotene.',
            'season': 'Spring',
            'difficulty': 'Intermediate',
            'sunlight': 'Full Sun',
            'watering': 'Moderate',
            'germination_days': 14,
            'spacing_cm': 7,
            'harvest_window_days': 30,
            'planting_tips': 'Prepare stone-free, loose sandy loam so roots grow straight without bifurcation.',
            'companion_plants': 'Rosmary, Sage, Lettuce, Chives'
        },
        {
            'name': 'San Marzano Tomato',
            'scientific_name': 'Solanum lycopersicum',
            'category': cat_map['vegetables'],
            'growth_days': 78,
            'image_url': 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?auto=format&fit=crop&w=800&q=80',
            'description': 'The premier Italian plum tomato with thick, fleshy walls, minimal seeds, and unmatched rich sweetness.',
            'season': 'Summer',
            'difficulty': 'Intermediate',
            'sunlight': 'Full Sun',
            'watering': 'High',
            'germination_days': 8,
            'spacing_cm': 60,
            'harvest_window_days': 45,
            'planting_tips': 'Prune suckers and stake securely. Water at the base to prevent foliage diseases.',
            'companion_plants': 'Basil, Marigolds, Garlic, Carrots'
        },
        {
            'name': 'Bell Pepper Trio',
            'scientific_name': 'Capsicum annuum',
            'category': cat_map['vegetables'],
            'growth_days': 75,
            'image_url': 'https://images.unsplash.com/photo-1563565375-f3fdfdbefa83?auto=format&fit=crop&w=800&q=80',
            'description': 'Crisp and juicy sweet bell peppers maturing from green into rich red, vibrant yellow, and orange.',
            'season': 'Summer',
            'difficulty': 'Intermediate',
            'sunlight': 'Full Sun',
            'watering': 'Moderate',
            'germination_days': 10,
            'spacing_cm': 45,
            'harvest_window_days': 30,
            'planting_tips': 'Requires warm soil to germinate and establish. Mulch well to retain moisture.',
            'companion_plants': 'Basil, Onions, Spinach'
        },
        {
            'name': 'Golden Bantam Sweet Corn',
            'scientific_name': 'Zea mays var. saccharata',
            'category': cat_map['legumes-pods'],
            'growth_days': 82,
            'image_url': 'https://images.unsplash.com/photo-1551754655-cd27e38d2076?auto=format&fit=crop&w=800&q=80',
            'description': 'Classic heirloom sweet yellow corn boasting succulent kernels packed with old-fashioned corn flavor.',
            'season': 'Summer',
            'difficulty': 'Intermediate',
            'sunlight': 'Full Sun',
            'watering': 'High',
            'germination_days': 7,
            'spacing_cm': 30,
            'harvest_window_days': 10,
            'planting_tips': 'Plant in blocks of at least 4 rows rather than a single long row to ensure wind pollination.',
            'companion_plants': 'Beans, Squash, Melons, Cucumbers'
        },
        {
            'name': 'Crimson Sweet Watermelon',
            'scientific_name': 'Citrullus lanatus',
            'category': cat_map['fruits-berries'],
            'growth_days': 88,
            'image_url': 'https://images.unsplash.com/photo-1587049352846-4a222e784d38?auto=format&fit=crop&w=800&q=80',
            'description': 'Heavy, striped melons with honey-sweet crimson flesh and high sugar content for hot summer days.',
            'season': 'Summer',
            'difficulty': 'Intermediate',
            'sunlight': 'Full Sun',
            'watering': 'High',
            'germination_days': 8,
            'spacing_cm': 90,
            'harvest_window_days': 15,
            'planting_tips': 'Look for a dried tendril and yellowish field spot on the underside when testing ripeness.',
            'companion_plants': 'Corn, Radishes, Marigolds'
        },
        {
            'name': 'Yukon Gold Potato',
            'scientific_name': 'Solanum tuberosum',
            'category': cat_map['root-vegetables'],
            'growth_days': 95,
            'image_url': 'https://images.unsplash.com/photo-1518977676601-b53f82aba655?auto=format&fit=crop&w=800&q=80',
            'description': 'Creamy, rich golden flesh with buttery flavor suitable for boiling, baking, and silky mashed potatoes.',
            'season': 'Spring',
            'difficulty': 'Intermediate',
            'sunlight': 'Full Sun',
            'watering': 'Moderate',
            'germination_days': 14,
            'spacing_cm': 35,
            'harvest_window_days': 30,
            'planting_tips': 'Hill soil around stems as they grow to prevent green tubers and maximize yield.',
            'companion_plants': 'Beans, Horseradish, Marigolds'
        },
        {
            'name': 'Eversweet Strawberry',
            'scientific_name': 'Fragaria x ananassa',
            'category': cat_map['fruits-berries'],
            'growth_days': 100,
            'image_url': 'https://images.unsplash.com/photo-1464965911861-746a04b4bca6?auto=format&fit=crop&w=800&q=80',
            'description': 'Prolific everbearing variety yielding glossy, aromatic red strawberries throughout summer and fall.',
            'season': 'Spring',
            'difficulty': 'Intermediate',
            'sunlight': 'Full Sun',
            'watering': 'Moderate',
            'germination_days': 21,
            'spacing_cm': 30,
            'harvest_window_days': 60,
            'planting_tips': 'Keep the crown at soil level when planting. Use straw mulch to keep berries off damp ground.',
            'companion_plants': 'Spinach, Borage, Thyme, Lettuce'
        },
        {
            'name': 'Cinderella Pumpkin',
            'scientific_name': 'Cucurbita maxima',
            'category': cat_map['vegetables'],
            'growth_days': 110,
            'image_url': 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=800&q=80',
            'description': 'French heirloom heirloom rouge vif detampes with deeply ribbed, glowing scarlet skin and sweet custard flesh.',
            'season': 'Summer',
            'difficulty': 'Intermediate',
            'sunlight': 'Full Sun',
            'watering': 'High',
            'germination_days': 10,
            'spacing_cm': 120,
            'harvest_window_days': 30,
            'planting_tips': 'Give vines plenty of room to wander. Harvest before heavy hard frost with stem intact.',
            'companion_plants': 'Corn, Marigolds, Oregano'
        },
        {
            'name': 'Tuscan Blue Rosemary',
            'scientific_name': 'Salvia rosmarinus',
            'category': cat_map['herbs-aromatics'],
            'growth_days': 90,
            'image_url': 'https://images.unsplash.com/photo-1515586000433-a5bc720b3624?auto=format&fit=crop&w=800&q=80',
            'description': 'Robust upright perennial herb with resinous pine needle aroma and vivid violet-blue blossoms.',
            'season': 'All Season',
            'difficulty': 'Easy',
            'sunlight': 'Full Sun',
            'watering': 'Low',
            'germination_days': 21,
            'spacing_cm': 45,
            'harvest_window_days': 365,
            'planting_tips': 'Extremely drought tolerant once established. Prefers well-draining, gravelly soil.',
            'companion_plants': 'Carrots, Cabbage, Beans'
        },
        {
            'name': 'Hardneck Purple Garlic',
            'scientific_name': 'Allium sativum var. ophioscorodon',
            'category': cat_map['root-vegetables'],
            'growth_days': 210,
            'image_url': 'https://images.unsplash.com/photo-1540148426945-6cf22a6b2383?auto=format&fit=crop&w=800&q=80',
            'description': 'Rich pungent gourmet garlic with purple striped cloves and delicious spring flower scapes.',
            'season': 'Autumn',
            'difficulty': 'Easy',
            'sunlight': 'Full Sun',
            'watering': 'Moderate',
            'germination_days': 14,
            'spacing_cm': 15,
            'harvest_window_days': 30,
            'planting_tips': 'Plant cloves in late autumn before ground freezes for hearty mid-summer harvest.',
            'companion_plants': 'Tomatoes, Peppers, Roses'
        },
        {
            'name': 'Zucchini',
            'scientific_name': 'Cucurbita pepo',
            'category': cat_map['vegetables'],
            'growth_days': 50,
            'image_url': 'https://images.unsplash.com/photo-1593642634367-d91a135587b3?auto=format&fit=crop&w=800&q=80',
            'description': 'Summer squash with tender, edible fruit. Prolific producer ideal for small spaces.',
            'season': 'Summer',
            'difficulty': 'Easy',
            'sunlight': 'Full Sun',
            'watering': 'Moderate',
            'germination_days': 7,
            'spacing_cm': 60,
            'harvest_window_days': 30,
            'planting_tips': 'Harvest frequently when fruits are small (15-20cm) to encourage continued production.',
            'companion_plants': 'Corn, Nasturtium, Peppermint'
        },
        {
            'name': 'Yellow Squash',
            'scientific_name': 'Cucurbita pepo var. recticollis',
            'category': cat_map['vegetables'],
            'growth_days': 55,
            'image_url': 'https://images.unsplash.com/photo-1621043488753-2ebe5e5564e6?auto=format&fit=crop&w=800&q=80',
            'description': 'Bright yellow summer squash with tender flesh and mild flavor.',
            'season': 'Summer',
            'difficulty': 'Easy',
            'sunlight': 'Full Sun',
            'watering': 'Moderate',
            'germination_days': 7,
            'spacing_cm': 60,
            'harvest_window_days': 25,
            'planting_tips': 'Pick regularly to encourage continuous production throughout summer.',
            'companion_plants': 'Corn, Marigold, Oregano'
        },
        {
            'name': 'Kale',
            'scientific_name': 'Brassica oleracea var. sabellica',
            'category': cat_map['leafy-greens'],
            'growth_days': 60,
            'image_url': 'https://images.unsplash.com/photo-1592748814005-0277b3b2e5ed?auto=format&fit=crop&w=800&q=80',
            'description': 'Hardy, nutrient-dense leafy green with curly or flat leaves. Excellent for salads and cooking.',
            'season': 'Spring/Fall',
            'difficulty': 'Easy',
            'sunlight': 'Full Sun/Partial Shade',
            'watering': 'Moderate',
            'germination_days': 7,
            'spacing_cm': 45,
            'harvest_window_days': 30,
            'planting_tips': 'Harvest outer leaves first to allow center to continue growing. Sweeter after light frost.',
            'companion_plants': 'Beets, Celery, Herbs, Onions, Potatoes'
        },
        {
            'name': 'Swiss Chard',
            'scientific_name': 'Beta vulgaris subsp. cicla',
            'category': cat_map['leafy-greens'],
            'growth_days': 55,
            'image_url': 'https://images.unsplash.com/photo-1586190848861-96aa4a174293?auto=format&fit=crop&w=800&q=80',
            'description': 'Colorful leafy green with bright stalks and tender leaves. Heat-tolerant and productive.',
            'season': 'Spring/Fall',
            'difficulty': 'Easy',
            'sunlight': 'Full Sun/Partial Shade',
            'watering': 'Moderate',
            'germination_days': 7,
            'spacing_cm': 30,
            'harvest_window_days': 60,
            'planting_tips': 'Harvest outer leaves continuously. Tolerates heat better than spinach.',
            'companion_plants': 'Beans, Cabbage, Onions, Tomatoes'
        },
        {
            'name': 'Arugula',
            'scientific_name': 'Eruca vesicaria',
            'category': cat_map['leafy-greens'],
            'growth_days': 40,
            'image_url': 'https://images.unsplash.com/photo-1581788555514-33f8ae74876e?auto=format&fit=crop&w=800&q=80',
            'description': 'Peppery, fast-growing leafy green. Adds spicy kick to salads and sandwiches.',
            'season': 'Spring/Fall',
            'difficulty': 'Easy',
            'sunlight': 'Full Sun/Partial Shade',
            'watering': 'Moderate',
            'germination_days': 5,
            'spacing_cm': 15,
            'harvest_window_days': 30,
            'planting_tips': 'Harvest young leaves for best flavor. Bolts quickly in heat - plant in succession.',
            'companion_plants': 'Beets, Carrots, Cucumbers, Onions'
        },
        {
            'name': 'Blueberry',
            'scientific_name': 'Vaccinium corymbosum',
            'category': cat_map['fruits-berries'],
            'growth_days': 730,
            'image_url': 'https://images.unsplash.com/photo-1573194475115-8693582b4c07?auto=format&fit=crop&w=800&q=80',
            'description': 'Antioxidant-rich berries on deciduous shrubs. Requires acidic soil for best results.',
            'season': 'Summer',
            'difficulty': 'Medium',
            'sunlight': 'Full Sun',
            'watering': 'High',
            'germination_days': 30,
            'spacing_cm': 150,
            'harvest_window_days': 30,
            'planting_tips': 'Plant in acidic soil (pH 4.5-5.5). Mulch with pine needles or oak leaves.',
            'companion_plants': 'Cranberries, Ferns, Holly, Rhododendrons'
        },
        {
            'name': 'Raspberry',
            'scientific_name': 'Rubus idaeus',
            'category': cat_map['fruits-berries'],
            'growth_days': 365,
            'image_url': 'https://images.unsplash.com/photo-1578974494381-04ecabc3b50c?auto=format&fit=crop&w=800&q=80',
            'description': 'Aggregate fruit with sweet-tart flavor. Produces on biennial canes.',
            'season': 'Summer/Fall',
            'difficulty': 'Medium',
            'sunlight': 'Full Sun',
            'watering': 'Moderate',
            'germination_days': 30,
            'spacing_cm': 60,
            'harvest_window_days': 30,
            'planting_tips': 'Prune spent canes after fruiting. Provide support for trailing varieties.',
            'companion_plants': 'Garlic, Lavender, Onions, Rosemary, Tansy'
        },
        {
            'name': 'Cantaloupe',
            'scientific_name': 'Cucumis melo var. cantalupensis',
            'category': cat_map['fruits-berries'],
            'growth_days': 80,
            'image_url': 'https://images.unsplash.com/photo-1585547678975-5d4b4b4d8b66?auto=format&fit=crop&w=800&q=80',
            'description': 'Sweet, fragrant melon with netted rind and orange flesh. Warm-weather favorite.',
            'season': 'Summer',
            'difficulty': 'Medium',
            'sunlight': 'Full Sun',
            'watering': 'High',
            'germination_days': 7,
            'spacing_cm': 90,
            'harvest_window_days': 15,
            'planting_tips': 'Harvest when stem separates easily from fruit. Strong fragrance indicates ripeness.',
            'companion_plants': 'Corn, Marigold, Nasturtium, Radishes'
        },
        {
            'name': 'Beet',
            'scientific_name': 'Beta vulgaris',
            'category': cat_map['root-vegetables'],
            'growth_days': 60,
            'image_url': 'https://images.unsplash.com/photo-1578328656961-56b90a8aac0b?auto=format&fit=crop&w=800&q=80',
            'description': 'Dual-purpose crop producing both nutritious roots and edible greens. Comes in red, gold, and striped varieties.',
            'season': 'Spring/Fall',
            'difficulty': 'Easy',
            'sunlight': 'Full Sun',
            'watering': 'Moderate',
            'germination_days': 5,
            'spacing_cm': 10,
            'harvest_window_days': 14,
            'planting_tips': 'Thin to proper spacing early. Both roots and greens are edible.',
            'companion_plants': 'Bush Beans, Cabbage, Lettuce, Onions'
        },
        {
            'name': 'Turnip',
            'scientific_name': 'Brassica rapa subsp. rapa',
            'category': cat_map['root-vegetables'],
            'growth_days': 50,
            'image_url': 'https://images.unsplash.com/photo-1582722573409-33b5b5b5a8b6?auto=format&fit=crop&w=800&q=80',
            'description': 'Fast-growing root crop with both edible roots and greens. Popular in European and Asian cuisines.',
            'season': 'Spring/Fall',
            'difficulty': 'Easy',
            'sunlight': 'Full Sun',
            'watering': 'Moderate',
            'germination_days': 3,
            'spacing_cm': 15,
            'harvest_window_days': 14,
            'planting_tips': 'Harvest small (5-7cm diameter) for best texture and flavor. Greens ready in 30 days.',
            'companion_plants': 'Peas, Vetch'
        },
        {
            'name': 'Radish (Cherry Belle)',
            'scientific_name': 'Raphanus sativus \'Cherry Belle\'',
            'category': cat_map['root-vegetables'],
            'growth_days': 25,
            'image_url': 'https://images.unsplash.com/photo-1595791559765-2ec7a0b6b543?auto=format&fit=crop&w=800&q=80',
            'description': 'Classic round red radish with white interior. Crisp and mild when harvested young.',
            'season': 'Spring/Fall',
            'difficulty': 'Easy',
            'sunlight': 'Full Sun',
            'watering': 'Moderate',
            'germination_days': 4,
            'spacing_cm': 5,
            'harvest_window_days': 7,
            'planting_tips': 'Sow every 10-14 days for continuous harvest. Best flavor when harvested small.',
            'companion_plants': 'Carrots, Cucumbers, Lettuce, Nasturtium'
        },
        {
            'name': 'Parsley',
            'scientific_name': 'Petroselinum crispum',
            'category': cat_map['herbs-aromatics'],
            'growth_days': 70,
            'image_url': 'https://images.unsplash.com/photo-1596498937883-a4461d90de35?auto=format&fit=crop&w=800&q=80',
            'description': 'Biennial herb with flat or curly leaves. Rich in vitamins A, C, and K.',
            'season': 'Spring/Summer/Fall',
            'difficulty': 'Easy',
            'sunlight': 'Full Sun/Partial Shade',
            'watering': 'Moderate',
            'germination_days': 14,
            'spacing_cm': 20,
            'harvest_window_days': 90,
            'planting_tips': 'Slow to germinate - soak seeds overnight before planting. Cut-and-come-again harvesting.',
            'companion_plants': 'Asparagus, Corn, Roses, Tomatoes'
        },
        {
            'name': 'Cilantro',
            'scientific_name': 'Coriandrum sativum',
            'category': cat_map['herbs-aromatics'],
            'growth_days': 45,
            'image_url': 'https://images.unsplash.com/photo-1589842755669-7f7a5ac4b752?auto=format&fit=crop&w=800&q=80',
            'description': 'Pungent herb essential to many cuisines. Seeds are coriander spice.',
            'season': 'Spring/Fall',
            'difficulty': 'Easy',
            'sunlight': 'Full Sun/Partial Shade',
            'watering': 'Moderate',
            'germination_days': 7,
            'spacing_cm': 20,
            'harvest_window_days': 30,
            'planting_tips': 'Bolts quickly in heat - plant in succession for continuous harvest. Leaves and seeds both used.',
            'companion_plants': 'Anise, Caraway, Potatoes, Spinach'
        },
        {
            'name': 'Dill',
            'scientific_name': 'Anethum graveolens',
            'category': cat_map['herbs-aromatics'],
            'growth_days': 70,
            'image_url': 'https://images.unsplash.com/photo-1596483361280-38b3b3b54a12?auto=format&fit=crop&w=800&q=80',
            'description': 'Feathery herb with yellow flowers. Both leaves (dill weed) and seeds (dill seed) used.',
            'season': 'Summer',
            'difficulty': 'Easy',
            'sunlight': 'Full Sun',
            'watering': 'Moderate',
            'germination_days': 7,
            'spacing_cm': 30,
            'harvest_window_days': 60,
            'planting_tips': 'Attracts beneficial insects. Avoid planting near carrots as it may stunt their growth.',
            'companion_plants': 'Cabbage, Corn, Cucumbers, Lettuce, Onions'
        },
        {
            'name': 'Bush Bean (Provider)',
            'scientific_name': 'Phaseolus vulgaris \'Provider\'',
            'category': cat_map['legumes-pods'],
            'growth_days': 55,
            'image_url': 'https://images.unsplash.com/photo-1598470029341-3245274b450b?auto=format&fit=crop&w=800&q=80',
            'description': 'Early-producing, disease-resistant bush bean. Reliable producer in various conditions.',
            'season': 'Summer',
            'difficulty': 'Easy',
            'sunlight': 'Full Sun',
            'watering': 'Moderate',
            'germination_days': 8,
            'spacing_cm': 15,
            'harvest_window_days': 30,
            'planting_tips': 'Harvest pods when young and tender. Regular picking encourages continued production.',
            'companion_plants': 'Corn, Cucumbers, Eggplant, Radishes'
        },
        {
            'name': 'English Pea',
            'scientific_name': 'Pisum sativum',
            'category': cat_map['legumes-pods'],
            'growth_days': 65,
            'image_url': 'https://images.unsplash.com/photo-1583195261899-2b7b5b5b8b66?auto=format&fit=crop&w=800&q=80',
            'description': 'Traditional shelling pea with sweet peas inside fibrous pods. Cool-season favorite.',
            'season': 'Spring',
            'difficulty': 'Easy',
            'sunlight': 'Full Sun/Partial Shade',
            'watering': 'Moderate',
            'germination_days': 10,
            'spacing_cm': 10,
            'harvest_window_days': 14,
            'planting_tips': 'Provide trellis or support for climbing varieties. Harvest when pods are plump but not bulging.',
            'companion_plants': 'Carrots, Corn, Cucumbers, Radishes, Turnips'
        },
        {
            'name': 'Lentils',
            'scientific_name': 'Lens culinaris',
            'category': cat_map['legumes-pods'],
            'growth_days': 110,
            'image_url': 'https://images.unsplash.com/photo-1596492199582-43b3b3b54a12?auto=format&fit=crop&w=800&q=80',
            'description': 'Ancient legume producing lens-shaped seeds in pods. Drought-tolerant and nitrogen-fixing.',
            'season': 'Spring',
            'difficulty': 'Medium',
            'sunlight': 'Full Sun',
            'watering': 'Low',
            'germination_days': 10,
            'spacing_cm': 5,
            'harvest_window_days': 21,
            'planting_tips': 'Harvest when pods turn brown and seeds rattle inside. Excellent for soil improvement.',
            'companion_plants': 'Celery, Potatoes'
        },
        {
            'name': 'Moro Blood Orange',
            'scientific_name': 'Citrus sinensis \'Moro\'',
            'category': cat_map['fruits-berries'],
            'growth_days': 730,
            'image_url': 'https://images.unsplash.com/photo-1582719478250-59492a879546?auto=format&fit=crop&w=800&q=80',
            'description': 'Distinctive blood orange with deep crimson flesh and sweet raspberry-like notes. Rich in antioxidants and vitamin C.',
            'season': 'Winter',
            'difficulty': 'Medium',
            'sunlight': 'Full Sun',
            'watering': 'Moderate',
            'germination_days': 21,
            'spacing_cm': 450,
            'harvest_window_days': 90,
            'planting_tips': 'Plant in well-draining soil. Protect from frost. Fruit develops best color with cool night temperatures.',
            'companion_plants': 'Lavender, Rosemary, Marigolds'
        },
        {
            'name': 'Honeycrisp Apple',
            'scientific_name': 'Malus domestica \'Honeycrisp\'',
            'category': cat_map['fruits-berries'],
            'growth_days': 1460,
            'image_url': 'https://images.unsplash.com/photo-1560806887-1e4cd0b6c9bd?auto=format&fit=crop&w=800&q=80',
            'description': 'Sweet-tart apples with explosive crispness. Developed in Minnesota, perfect for cold climates.',
            'season': 'Autumn',
            'difficulty': 'Medium',
            'sunlight': 'Full Sun',
            'watering': 'Moderate',
            'germination_days': 30,
            'spacing_cm': 450,
            'harvest_window_days': 60,
            'planting_tips': 'Requires cross-pollination. Prune in late winter. Thin fruit for larger size.',
            'companion_plants': 'Garlic, Chives, Marigolds'
        },
        {
            'name': 'Navel Orange',
            'scientific_name': 'Citrus sinensis',
            'category': cat_map['fruits-berries'],
            'growth_days': 1095,
            'image_url': 'https://images.unsplash.com/photo-1582719478250-59492a879546?auto=format&fit=crop&w=800&q=80',
            'description': 'Seedless sweet oranges with easy-to-peel skin. Most popular eating orange worldwide.',
            'season': 'Winter',
            'difficulty': 'Medium',
            'sunlight': 'Full Sun',
            'watering': 'Moderate',
            'germination_days': 21,
            'spacing_cm': 450,
            'harvest_window_days': 90,
            'planting_tips': 'Plant in well-draining soil. Protect from frost. Fertilize in spring and summer.',
            'companion_plants': 'Lavender, Rosemary, Marigolds'
        },
        {
            'name': 'Eureka Lemon',
            'scientific_name': 'Citrus limon \'Eureka\'',
            'category': cat_map['fruits-berries'],
            'growth_days': 1095,
            'image_url': 'https://images.unsplash.com/photo-1582719478250-59492a879546?auto=format&fit=crop&w=800&q=80',
            'description': 'Year-round producing lemon with classic tart flavor. Thornless variety ideal for home gardens.',
            'season': 'All Season',
            'difficulty': 'Medium',
            'sunlight': 'Full Sun',
            'watering': 'Moderate',
            'germination_days': 21,
            'spacing_cm': 300,
            'harvest_window_days': 365,
            'planting_tips': 'Protect from frost. Prune to maintain shape. Fertilize every 6 weeks during growing season.',
            'companion_plants': 'Thyme, Rosemary, Marigolds'
        },
        {
            'name': 'Redhaven Peach',
            'scientific_name': 'Prunus persica \'Redhaven\'',
            'category': cat_map['fruits-berries'],
            'growth_days': 1095,
            'image_url': 'https://images.unsplash.com/photo-1581923042631-86b7a6437bca?auto=format&fit=crop&w=800&q=80',
            'description': 'Classic freestone peach with red-blushed skin and sweet yellow flesh. Most widely planted peach variety.',
            'season': 'Summer',
            'difficulty': 'Medium',
            'sunlight': 'Full Sun',
            'watering': 'Moderate',
            'germination_days': 30,
            'spacing_cm': 450,
            'harvest_window_days': 30,
            'planting_tips': 'Plant in well-draining soil. Prune to open center shape. Thin fruit to 6-8 inches apart.',
            'companion_plants': 'Garlic, Chives, Tansy'
        },
        {
            'name': 'Bartlett Pear',
            'scientific_name': 'Pyrus communis \'Bartlett\'',
            'category': cat_map['fruits-berries'],
            'growth_days': 1095,
            'image_url': 'https://images.unsplash.com/photo-1582719478250-59492a879546?auto=format&fit=crop&w=800&q=80',
            'description': 'America\'s most popular pear. Juicy and sweet when ripe, excellent for canning and fresh eating.',
            'season': 'Autumn',
            'difficulty': 'Medium',
            'sunlight': 'Full Sun',
            'watering': 'Moderate',
            'germination_days': 30,
            'spacing_cm': 450,
            'harvest_window_days': 30,
            'planting_tips': 'Plant in well-draining soil. Prune to central leader shape. Harvest when green and ripen indoors.',
            'companion_plants': 'Garlic, Chives, Nasturtium'
        },
        {
            'name': 'Rainbow Chard',
            'scientific_name': 'Beta vulgaris subsp. cicla',
            'category': cat_map['leafy-greens'],
            'growth_days': 55,
            'image_url': 'https://images.unsplash.com/photo-1586190848861-96aa4a174293?auto=format&fit=crop&w=800&q=80',
            'description': 'Colorful stems in red, pink, orange, yellow and white with green leaves. Both ornamental and edible.',
            'season': 'Spring/Fall',
            'difficulty': 'Easy',
            'sunlight': 'Full Sun/Partial Shade',
            'watering': 'Moderate',
            'germination_days': 7,
            'spacing_cm': 30,
            'harvest_window_days': 60,
            'planting_tips': 'Harvest outer leaves continuously. Tolerates heat better than spinach.',
            'companion_plants': 'Beans, Cabbage, Onions, Tomatoes'
        },
        {
            'name': 'Frisee Endive',
            'scientific_name': 'Cichorium endivia var. crispum',
            'category': cat_map['leafy-greens'],
            'growth_days': 45,
            'image_url': 'https://images.unsplash.com/photo-1582719478250-59492a879546?auto=format&fit=crop&w=800&q=80',
            'description': 'Frilly, bitter green that adds texture and depth to salads. Blanched centers are pale yellow.',
            'season': 'Spring/Fall',
            'difficulty': 'Medium',
            'sunlight': 'Full Sun/Partial Shade',
            'watering': 'Moderate',
            'germination_days': 5,
            'spacing_cm': 20,
            'harvest_window_days': 30,
            'planting_tips': 'Blanch by tying outer leaves 2 weeks before harvest for milder flavor.',
            'companion_plants': 'Radishes, Carrots, Onions'
        },
        {
            'name': 'Mizuna',
            'scientific_name': 'Brassica rapa var. nipposinica',
            'category': cat_map['leafy-greens'],
            'growth_days': 40,
            'image_url': 'https://images.unsplash.com/photo-1582719478250-59492a879546?auto=format&fit=crop&w=800&q=80',
            'description': 'Japanese mustard green with feathery, mildly peppery leaves. Popular in salad mixes.',
            'season': 'Spring/Fall',
            'difficulty': 'Easy',
            'sunlight': 'Full Sun/Partial Shade',
            'watering': 'Moderate',
            'germination_days': 4,
            'spacing_cm': 15,
            'harvest_window_days': 30,
            'planting_tips': 'Cut-and-come-again harvesting. Tolerates light frost.',
            'companion_plants': 'Carrots, Onions, Peas'
        },
        {
            'name': 'Tatsoi',
            'scientific_name': 'Brassica rapa subsp. narinosa',
            'category': cat_map['leafy-greens'],
            'growth_days': 45,
            'image_url': 'https://images.unsplash.com/photo-1582719478250-59492a879546?auto=format&fit=crop&w=800&q=80',
            'description': 'Spoon-shaped leaves forming compact rosettes. Mild mustard flavor, excellent raw or cooked.',
            'season': 'Spring/Fall',
            'difficulty': 'Easy',
            'sunlight': 'Full Sun/Partial Shade',
            'watering': 'Moderate',
            'germination_days': 4,
            'spacing_cm': 20,
            'harvest_window_days': 30,
            'planting_tips': 'Harvest whole plant or pick outer leaves. Sweeter after light frost.',
            'companion_plants': 'Carrots, Onions, Peas'
        },
        {
            'name': 'Watermelon Radish',
            'scientific_name': 'Raphanus sativus',
            'category': cat_map['root-vegetables'],
            'growth_days': 60,
            'image_url': 'https://images.unsplash.com/photo-1593105544559-ecb03bf76f82?auto=format&fit=crop&w=800&q=80',
            'description': 'White exterior with stunning bright pink-red interior. Mild, sweet flavor with slight peppery notes.',
            'season': 'Spring/Fall',
            'difficulty': 'Easy',
            'sunlight': 'Full Sun',
            'watering': 'Moderate',
            'germination_days': 4,
            'spacing_cm': 10,
            'harvest_window_days': 14,
            'planting_tips': 'Harvest at 2-4 inches diameter for best texture. Great raw in salads or roasted.',
            'companion_plants': 'Carrots, Lettuce, Peas'
        },
        {
            'name': 'Daikon Radish',
            'scientific_name': 'Raphanus sativus var. longipinnatus',
            'category': cat_map['root-vegetables'],
            'growth_days': 60,
            'image_url': 'https://images.unsplash.com/photo-1593105544559-ecb03bf76f82?auto=format&fit=crop&w=800&q=80',
            'description': 'Large white winter radish popular in Asian cuisine. Can grow up to 20 inches long.',
            'season': 'Autumn/Winter',
            'difficulty': 'Easy',
            'sunlight': 'Full Sun',
            'watering': 'Moderate',
            'germination_days': 4,
            'spacing_cm': 15,
            'harvest_window_days': 14,
            'planting_tips': 'Harvest when roots are 2-3 inches diameter. Stores well in cool, humid conditions.',
            'companion_plants': 'Carrots, Lettuce, Peas'
        },
                        {
            'name': 'Genovese Basil',
            'scientific_name': 'Ocimum basilicum',
            'category': cat_map['herbs-aromatics'],
            'growth_days': 60,
            'image_url': 'https://images.unsplash.com/photo-1618164435735-413d3b066c9a?auto=format&fit=crop&w=800&q=80',
            'description': 'Classic sweet Italian basil with large leaves. Essential for pesto and caprese salad.',
            'season': 'Summer',
            'difficulty': 'Easy',
            'sunlight': 'Full Sun',
            'watering': 'Moderate',
            'germination_days': 5,
            'spacing_cm': 25,
            'harvest_window_days': 30,
            'planting_tips': 'Pinch flower buds to encourage leaf growth. Harvest in morning for best flavor.',
            'companion_plants': 'Tomatoes, Peppers, Oregano'
        },
        {
            'name': 'Thai Basil',
            'scientific_name': 'Ocimum basilicum var. thyrsiflora',
            'category': cat_map['herbs-aromatics'],
            'growth_days': 60,
            'image_url': 'https://images.unsplash.com/photo-1618164435735-413d3b066c9a?auto=format&fit=crop&w=800&q=80',
            'description': 'Spicy, anise-flavored basil with purple stems. Essential for Thai and Vietnamese cuisine.',
            'season': 'Summer',
            'difficulty': 'Easy',
            'sunlight': 'Full Sun',
            'watering': 'Moderate',
            'germination_days': 5,
            'spacing_cm': 20,
            'harvest_window_days': 30,
            'planting_tips': 'More heat tolerant than sweet basil. Pinch flower buds to prolong harvest.',
            'companion_plants': 'Tomatoes, Peppers, Eggplant'
        },
        {
            'name': 'Lemon Basil',
            'scientific_name': 'Ocimum × citriodorum',
            'category': cat_map['herbs-aromatics'],
            'growth_days': 60,
            'image_url': 'https://images.unsplash.com/photo-1618164435735-413d3b066c9a?auto=format&fit=crop&w=800&q=80',
            'description': 'Hybrid basil with strong lemon fragrance and flavor. Excellent with fish and poultry.',
            'season': 'Summer',
            'difficulty': 'Easy',
            'sunlight': 'Full Sun',
            'watering': 'Moderate',
            'germination_days': 5,
            'spacing_cm': 20,
            'harvest_window_days': 30,
            'planting_tips': 'More compact growth than sweet basil. Use fresh or dried.',
            'companion_plants': 'Tomatoes, Peppers, Eggplant'
        },
        {
            'name': 'Holy Basil (Tulsi)',
            'scientific_name': 'Ocimum tenuiflorum',
            'category': cat_map['herbs-aromatics'],
            'growth_days': 90,
            'image_url': 'https://images.unsplash.com/photo-1618164435735-413d3b066c9a?auto=format&fit=crop&w=800&q=80',
            'description': 'Sacred plant in Hinduism with clove-like fragrance. Used in tea and Ayurvedic medicine.',
            'season': 'Summer',
            'difficulty': 'Medium',
            'sunlight': 'Full Sun',
            'watering': 'Moderate',
            'germination_days': 7,
            'spacing_cm': 20,
            'harvest_window_days': 90,
            'planting_tips': 'Perennial in tropical climates. Pinch regularly to encourage bushy growth.',
            'companion_plants': 'Tomatoes, Peppers, Eggplant'
        },
        {
            'name': 'Flat-Leaf Parsley',
            'scientific_name': 'Petroselinum crispum var. neapolitanum',
            'category': cat_map['herbs-aromatics'],
            'growth_days': 75,
            'image_url': 'https://images.unsplash.com/photo-1596498937883-a4461d90de35?auto=format&fit=crop&w=800&q=80',
            'description': 'Also called Italian parsley. Stronger flavor than curly variety, preferred for cooking.',
            'season': 'Spring/Summer/Fall',
            'difficulty': 'Easy',
            'sunlight': 'Full Sun/Partial Shade',
            'watering': 'Moderate',
            'germination_days': 14,
            'spacing_cm': 20,
            'harvest_window_days': 90,
            'planting_tips': 'Soak seeds overnight before planting. Cut outer stems to encourage new growth.',
            'companion_plants': 'Asparagus, Corn, Roses, Tomatoes'
        },
        {
            'name': 'Curly Parsley',
            'scientific_name': 'Petroselinum crispum',
            'category': cat_map['herbs-aromatics'],
            'growth_days': 75,
            'image_url': 'https://images.unsplash.com/photo-1596498937883-a4461d90de35?auto=format&fit=crop&w=800&q=80',
            'description': 'Decorative curly leaves often used as garnish. Milder flavor than flat-leaf variety.',
            'season': 'Spring/Summer/Fall',
            'difficulty': 'Easy',
            'sunlight': 'Full Sun/Partial Shade',
            'watering': 'Moderate',
            'germination_days': 14,
            'spacing_cm': 20,
            'harvest_window_days': 90,
            'planting_tips': 'Soak seeds overnight before planting. Cut outer stems to encourage new growth.',
            'companion_plants': 'Asparagus, Corn, Roses, Tomatoes'
        },
        {
            'name': 'Common Sage',
            'scientific_name': 'Salvia officinalis',
            'category': cat_map['herbs-aromatics'],
            'growth_days': 90,
            'image_url': 'https://images.unsplash.com/photo-1596483361280-38b3b3b54a12?auto=format&fit=crop&w=800&q=80',
            'description': 'Woody perennial herb with gray-green leaves. Essential for stuffing and sausage.',
            'season': 'All Season',
            'difficulty': 'Easy',
            'sunlight': 'Full Sun',
            'watering': 'Low',
            'germination_days': 14,
            'spacing_cm': 45,
            'harvest_window_days': 365,
            'planting_tips': 'Prune in spring to encourage new growth. Avoid overwatering.',
            'companion_plants': 'Carrots, Cabbage, Beans'
        },
        {
            'name': 'Pineapple Sage',
            'scientific_name': 'Salvia elegans',
            'category': cat_map['herbs-aromatics'],
            'growth_days': 90,
            'image_url': 'https://images.unsplash.com/photo-1596483361280-38b3b3b54a12?auto=format&fit=crop&w=800&q=80',
            'description': 'Bright red flowers with pineapple-scented leaves. Attracts hummingbirds and butterflies.',
            'season': 'Summer/Fall',
            'difficulty': 'Easy',
            'sunlight': 'Full Sun',
            'watering': 'Moderate',
            'germination_days': 10,
            'spacing_cm': 60,
            'harvest_window_days': 120,
            'planting_tips': 'Flowers and leaves both edible. Use in teas, salads, and as garnish.',
            'companion_plants': 'Corn, Squash, Tomatoes'
        },
        {
            'name': 'Lemon Verbena',
            'scientific_name': 'Aloysia citrodora',
            'category': cat_map['herbs-aromatics'],
            'growth_days': 90,
            'image_url': 'https://images.unsplash.com/photo-1596483361280-38b3b3b54a12?auto=format&fit=crop&w=800&q=80',
            'description': 'Intensely lemon-scented leaves and flowers. Makes excellent tea and adds flavor to desserts.',
            'season': 'Summer',
            'difficulty': 'Medium',
            'sunlight': 'Full Sun',
            'watering': 'Low',
            'germination_days': 21,
            'spacing_cm': 60,
            'harvest_window_days': 180,
            'planting_tips': 'Woody perennial in warm climates. Protect from frost.',
            'companion_plants': 'Thyme, Oregano, Marigolds'
        },
        {
            'name': 'Kentucky Wonder Pole Bean',
            'scientific_name': 'Phaseolus vulgaris',
            'category': cat_map['legumes-pods'],
            'growth_days': 65,
            'image_url': 'https://images.unsplash.com/photo-1598470029341-3245274b450b?auto=format&fit=crop&w=800&q=80',
            'description': 'Heirloom pole bean producing 8-inch green pods. Reliable producer since 1850s.',
            'season': 'Summer',
            'difficulty': 'Easy',
            'sunlight': 'Full Sun',
            'watering': 'Moderate',
            'germination_days': 8,
            'spacing_cm': 15,
            'harvest_window_days': 30,
            'planting_tips': 'Requires trellis or poles 6-8 feet high. Harvest regularly for continued production.',
            'companion_plants': 'Corn, Cucumbers, Eggplant, Radishes'
        },
                {
            'name': 'Dragon Tongue Bean',
            'scientific_name': 'Phaseolus vulgaris',
            'category': cat_map['legumes-pods'],
            'growth_days': 60,
            'image_url': 'https://images.unsplash.com/photo-1598470029341-3245274b450b?auto=format&fit=crop&w=800&q=80',
            'description': 'Heirloom wax bean with yellow pods streaked with purple. Excellent snap or shell bean.',
            'season': 'Summer',
            'difficulty': 'Easy',
            'sunlight': 'Full Sun',
            'watering': 'Moderate',
            'germination_days': 7,
            'spacing_cm': 15,
            'harvest_window_days': 30,
            'planting_tips': 'Pods lose purple streaks when cooked. Harvest young for best flavor as snap bean.',
            'companion_plants': 'Corn, Cucumbers, Eggplant, Radishes'
        },
        {
            'name': 'Fordhook Giant Lima Bean',
            'scientific_name': 'Phaseolus lunatus',
            'category': cat_map['legumes-pods'],
            'growth_days': 75,
            'image_url': 'https://images.unsplash.com/photo-1598470029341-3245274b450b?auto=format&fit=crop&w=800&q=80',
            'description': 'Large-seeded lima bean producing 4-inch pods. Reliable producer in warm climates.',
            'season': 'Summer',
            'difficulty': 'Medium',
            'sunlight': 'Full Sun',
            'watering': 'Moderate',
            'germination_days': 7,
            'spacing_cm': 15,
            'harvest_window_days': 30,
            'planting_tips': 'Requires warm soil to germinate. Needs long season for full pod development.',
            'companion_plants': 'Corn, Eggplant, Potatoes'
        },
        {
            'name': 'California Blackeye Pea',
            'scientific_name': 'Vigna unguiculata',
            'category': cat_map['legumes-pods'],
            'growth_days': 80,
            'image_url': 'https://images.unsplash.com/photo-1598470029341-3245274b450b?auto=format&fit=crop&w=800&q=80',
            'description': 'Also called black-eyed pea or cowpea. Cream-colored bean with distinctive black eye.',
            'season': 'Summer',
            'difficulty': 'Easy',
            'sunlight': 'Full Sun',
            'watering': 'Low',
            'germination_days': 5,
            'spacing_cm': 10,
            'harvest_window_days': 30,
            'planting_tips': 'Drought-tolerant once established. Plant after soil warms to 65°F.',
            'companion_plants': 'Corn, Eggplant, Potatoes'
        },
        {
            'name': 'Ladyfinger Okra',
            'scientific_name': 'Abelmoschus esculentus',
            'category': cat_map['legumes-pods'],
            'growth_days': 60,
            'image_url': 'https://images.unsplash.com/photo-1596492199582-43b3b3b54a12?auto=format&fit=crop&w=800&q=80',
            'description': 'Spineless variety producing tender green pods. Essential for gumbo and stews.',
            'season': 'Summer',
            'difficulty': 'Easy',
            'sunlight': 'Full Sun',
            'watering': 'Low',
            'germination_days': 7,
            'spacing_cm': 30,
            'harvest_window_days': 30,
            'planting_tips': 'Harvest pods when 2-4 inches long. Wear gloves when harvesting some varieties.',
            'companion_plants': 'Peppers, Eggplant, Melons'
        },
        {
            'name': 'Burgundy Okra',
            'scientific_name': 'Abelmoschus esculentus',
            'category': cat_map['legumes-pods'],
            'growth_days': 60,
            'image_url': 'https://images.unsplash.com/photo-1596492199582-43b3b3b54a12?auto=format&fit=crop&w=800&q=80',
            'description': 'Striking red pods and stems. Same green interior and flavor as green okra varieties.',
            'season': 'Summer',
            'difficulty': 'Easy',
            'sunlight': 'Full Sun',
            'watering': 'Low',
            'germination_days': 7,
            'spacing_cm': 30,
            'harvest_window_days': 30,
            'planting_tips': 'Harvest pods when 2-4 inches long. Color fades when cooked but adds visual appeal.',
            'companion_plants': 'Peppers, Eggplant, Melons'
        },
        {
            'name': 'Black Krim Tomato',
            'scientific_name': 'Solanum lycopersicum',
            'category': cat_map['vegetables'],
            'growth_days': 75,
            'image_url': 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?auto=format&fit=crop&w=800&q=80',
            'description': 'Russian heirloom with dark purple-black shoulders and rich, salty-sweet flavor.',
            'season': 'Summer',
            'difficulty': 'Medium',
            'sunlight': 'Full Sun',
            'watering': 'High',
            'germination_days': 7,
            'spacing_cm': 60,
            'harvest_window_days': 45,
            'planting_tips': 'Prune indeterminate vines. Prevent blossom end rot with consistent watering.',
            'companion_plants': 'Basil, Marigolds, Garlic, Carrots'
        },
        {
            'name': 'Green Zebra Tomato',
            'scientific_name': 'Solanum lycopersicum',
            'category': cat_map['vegetables'],
            'growth_days': 75,
            'image_url': 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?auto=format&fit=crop&w=800&q=80',
            'description': 'Yellow-green striped fruit with tangy flavor. Unique appearance and excellent taste.',
            'season': 'Summer',
            'difficulty': 'Medium',
            'sunlight': 'Full Sun',
            'watering': 'High',
            'germination_days': 7,
            'spacing_cm': 60,
            'harvest_window_days': 45,
            'planting_tips': 'Prune indeterminate vines. Fruit stays green-striped even when ripe.',
            'companion_plants': 'Basil, Marigolds, Garlic, Carrots'
        },
        {
            'name': 'Cherokee Purple Tomato',
            'scientific_name': 'Solanum lycopersicum',
            'category': cat_map['vegetables'],
            'growth_days': 80,
            'image_url': 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?auto=format&fit=crop&w=800&q=80',
            'description': 'Native American heirloom with dusky pink-purple flesh and sweet, rich flavor.',
            'season': 'Summer',
            'difficulty': 'Medium',
            'sunlight': 'Full Sun',
            'watering': 'High',
            'germination_days': 7,
            'spacing_cm': 60,
            'harvest_window_days': 45,
            'planting_tips': 'Prune indeterminate vines. One of the most flavorful heirloom varieties.',
            'companion_plants': 'Basil, Marigolds, Garlic, Carrots'
        },
        {
            'name': 'Sun Gold Tomato',
            'scientific_name': 'Solanum lycopersicum',
            'category': cat_map['vegetables'],
            'growth_days': 65,
            'image_url': 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?auto=format&fit=crop&w=800&q=80',
            'description': 'Exceptionally sweet orange cherry tomato. Prolific producer in clusters.',
            'season': 'Summer',
            'difficulty': 'Easy',
            'sunlight': 'Full Sun',
            'watering': 'High',
            'germination_days': 5,
            'spacing_cm': 30,
            'harvest_window_days': 60,
            'planting_tips': 'Indeterminate variety requiring support. Resists cracking better than most cherries.',
            'companion_plants': 'Basil, Marigolds, Garlic, Carrots'
        },
        {
            'name': 'Sweet 100 Tomato',
            'scientific_name': 'Solanum lycopersicum',
            'category': cat_map['vegetables'],
            'growth_days': 65,
            'image_url': 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?auto=format&fit=crop&w=800&q=80',
            'description': 'Red cherry tomato producing long strands of 100+ fruits. Reliable and disease-resistant.',
            'season': 'Summer',
            'difficulty': 'Easy',
            'sunlight': 'Full Sun',
            'watering': 'High',
            'germination_days': 5,
            'spacing_cm': 30,
            'harvest_window_days': 60,
            'planting_tips': 'Indeterminate variety requiring support. Excellent for snacking and salads.',
            'companion_plants': 'Basil, Marigolds, Garlic, Carrots'
        },
        {
            'name': 'Early Girl Tomato',
            'scientific_name': 'Solanum lycopersicum',
            'category': cat_map['vegetables'],
            'growth_days': 55,
            'image_url': 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?auto=format&fit=crop&w=800&q=80',
            'description': 'True to its name - one of the earliest slicing tomatoes to mature. Dependable producer.',
            'season': 'Summer',
            'difficulty': 'Easy',
            'sunlight': 'Full Sun',
            'watering': 'High',
            'germination_days': 5,
            'spacing_cm': 45,
            'harvest_window_days': 30,
            'planting_tips': 'Indeterminate variety. Good choice for short-season areas or early harvest.',
            'companion_plants': 'Basil, Marigolds, Garlic, Carrots'
        },
        {
            'name': 'Beefsteak Tomato',
            'scientific_name': 'Solanum lycopersicum',
            'category': cat_map['vegetables'],
            'growth_days': 85,
            'image_url': 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?auto=format&fit=crop&w=800&q=80',
            'description': 'Large, meaty tomatoes often weighing over 1 pound each. Classic sandwich tomato.',
            'season': 'Summer',
            'difficulty': 'Medium',
            'sunlight': 'Full Sun',
            'watering': 'High',
            'germination_days': 7,
            'spacing_cm': 60,
            'harvest_window_days': 45,
            'planting_tips': 'Requires strong support. Prune for air flow to prevent disease in humid climates.',
            'companion_plants': 'Basil, Marigolds, Garlic, Carrots'
        },
        {
            'name': 'Roma VF Tomato',
            'scientific_name': 'Solanum lycopersicum',
            'category': cat_map['vegetables'],
            'growth_days': 75,
            'image_url': 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?auto=format&fit=crop&w=800&q=80',
            'description': 'Plum tomato bred for resistance to verticillium and fusarium wilt (VF). Ideal for sauces.',
            'season': 'Summer',
            'difficulty': 'Easy',
            'sunlight': 'Full Sun',
            'watering': 'High',
            'germination_days': 7,
            'spacing_cm': 45,
            'harvest_window_days': 30,
            'planting_tips': 'Determinate variety - compact growth. Harvest all at once for preserving.',
            'companion_plants': 'Basil, Marigolds, Garlic, Carrots'
        },
        {
            'name': 'Butternut Squash',
            'scientific_name': 'Cucurbita moschata',
            'category': cat_map['vegetables'],
            'growth_days': 105,
            'image_url': 'https://images.unsplash.com/photo-1593642634367-d91a135587b3?auto=format&fit=crop&w=800&q=80',
            'description': 'Tan, bell-shaped squash with sweet orange flesh. Excellent keeper for winter storage.',
            'season': 'Summer',
            'difficulty': 'Medium',
            'sunlight': 'Full Sun',
            'watering': 'High',
            'germination_days': 7,
            'spacing_cm': 120,
            'harvest_window_days': 60,
            'planting_tips': 'Cure in warm, humid place for 2 weeks after harvest for better storage.',
            'companion_plants': 'Corn, Marigolds, Oregano'
        },
        {
            'name': 'Acorn Squash',
            'scientific_name': 'Cucurbita pectoides',
            'category': cat_map['vegetables'],
            'growth_days': 85,
            'image_url': 'https://images.unsplash.com/photo-1593642634367-d91a135587b3?auto=format&fit=crop&w=800&q=80',
            'description': 'Dark green, acorn-shaped squash with yellow-orange flesh. Excellent baked or stuffed.',
            'season': 'Summer',
            'difficulty': 'Medium',
            'sunlight': 'Full Sun',
            'watering': 'High',
            'germination_days': 7,
            'spacing_cm': 100,
            'harvest_window_days': 45,
            'planting_tips': 'Harvest when skin is hard and dark green. Stores well in cool, dry place.',
            'companion_plants': 'Corn, Marigolds, Oregano'
        },
        {
            'name': 'Delicata Squash',
            'scientific_name': 'Cucurbita pepo',
            'category': cat_map['vegetables'],
            'growth_days': 90,
            'image_url': 'https://images.unsplash.com/photo-1593642634367-d91a135587b3?auto=format&fit=crop&w=800&q=80',
            'description': 'Cream-colored with green stripes. Edible thin skin eliminates need for peeling.',
            'season': 'Summer',
            'difficulty': 'Easy',
            'sunlight': 'Full Sun',
            'watering': 'High',
            'germination_days': 5,
            'spacing_cm': 90,
            'harvest_window_days': 45,
            'planting_tips': 'Also called peanut squash. Best eaten within 3 months of harvest.',
            'companion_plants': 'Corn, Marigolds, Oregano'
        },
        {
            'name': 'Spaghetti Squash',
            'scientific_name': 'Cucurbita pepo',
            'category': cat_map['vegetables'],
            'growth_days': 95,
            'image_url': 'https://images.unsplash.com/photo-1593642634367-d91a135587b3?auto=format&fit=crop&w=800&q=80',
            'description': 'Yellow oval squash whose flesh separates into pasta-like strands when cooked.',
            'season': 'Summer',
            'difficulty': 'Medium',
            'sunlight': 'Full Sun',
            'watering': 'High',
            'germination_days': 7,
            'spacing_cm': 120,
            'harvest_window_days': 45,
            'planting_tips': 'Harvest when rind is hard and golden yellow. Stores well for winter use.',
            'companion_plants': 'Corn, Marigolds, Oregano'
        },
        {
            'name': 'Sugar Pie Pumpkin',
            'scientific_name': 'Cucurbita pepo',
            'category': cat_map['vegetables'],
            'growth_days': 100,
            'image_url': 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=800&q=80',
            'description': 'Small, sweet pumpkin perfect for pies. Dense, fine-grained orange flesh.',
            'season': 'Summer',
            'difficulty': 'Medium',
            'sunlight': 'Full Sun',
            'watering': 'High',
            'germination_days': 7,
            'spacing_cm': 120,
            'harvest_window_days': 30,
            'planting_tips': 'Harvest when rind is hard and deeply colored. Cure for better storage.',
            'companion_plants': 'Corn, Marigolds, Oregano'
        },
        {
            'name': 'Jack O\'Lantern Pumpkin',
            'scientific_name': 'Cucurbita pepo',
            'category': cat_map['vegetables'],
            'growth_days': 110,
            'image_url': 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=800&q=80',
            'description': 'Classic carving pumpkin with deep orange color and sturdy stem for handles.',
            'season': 'Summer',
            'difficulty': 'Medium',
            'sunlight': 'Full Sun',
            'watering': 'High',
            'germination_days': 7,
            'spacing_cm': 150,
            'harvest_window_days': 30,
            'planting_tips': 'For eating, choose smaller sugar pumpkins. Larger ones best for decoration.',
            'companion_plants': 'Corn, Marigolds, Oregano'
        },
        {
            'name': 'Atlantic Giant Pumpkin',
            'scientific_name': 'Cucurbita maxima',
            'category': cat_map['vegetables'],
            'growth_days': 130,
            'image_url': 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=800&q=80',
            'description': 'World record holder for largest pumpkin. Requires expert care and enormous space.',
            'season': 'Summer',
            'difficulty': 'Advanced',
            'sunlight': 'Full Sun',
            'watering': 'High',
            'germination_days': 7,
            'spacing_cm': 300,
            'harvest_window_days': 14,
            'planting_tips': 'Requires rich soil, constant moisture, and plenty of space. Not for beginners.',
            'companion_plants': 'None - needs isolation'
        },
        {
            'name': 'Blue Hubbard Squash',
            'scientific_name': 'Cucurbita maxima',
            'category': cat_map['vegetables'],
            'growth_days': 110,
            'image_url': 'https://images.unsplash.com/photo-1593642634367-d91a135587b3?auto=format&fit=crop&w=800&q=80',
            'description': 'Blue-gray, teardrop-shaped squash with sweet yellow flesh. Excellent winter keeper.',
            'season': 'Summer',
            'difficulty': 'Medium',
            'sunlight': 'Full Sun',
            'watering': 'High',
            'germination_days': 10,
            'spacing_cm': 180,
            'harvest_window_days': 60,
            'planting_tips': 'Very hard rind requires sturdy knife to cut. Stores 5-6 months in cool, dry place.',
            'companion_plants': 'Corn, Marigolds, Oregano'
        },
        {
            'name': 'California Wonder Bell Pepper',
            'scientific_name': 'Capsicum annuum',
            'category': cat_map['vegetables'],
            'growth_days': 75,
            'image_url': 'https://images.unsplash.com/photo-1563565375-f3fdfdbefa83?auto=format&fit=crop&w=800&q=80',
            'description': 'Classic large bell pepper. Blocky, thick-walled fruit that ripens from green to red.',
            'season': 'Summer',
            'difficulty': 'Medium',
            'sunlight': 'Full Sun',
            'watering': 'Moderate',
            'germination_days': 10,
            'spacing_cm': 45,
            'harvest_window_days': 30,
            'planting_tips': 'Requires warm soil to germinate. Stake plants to support heavy fruit.',
            'companion_plants': 'Basil, Onions, Spinach'
        },
        {
            'name': 'Jalapeño Early',
            'scientific_name': 'Capsicum annuum',
            'category': cat_map['vegetables'],
            'growth_days': 65,
            'image_url': 'https://images.unsplash.com/photo-1563565375-f3fdfdbefa83?auto=format&fit=crop&w=800&q=80',
            'description': 'Early-maturing jalapeño. Produces 3-inch dark green peppers that turn red when ripe.',
            'season': 'Summer',
            'difficulty': 'Medium',
            'sunlight': 'Full Sun',
            'watering': 'Moderate',
            'germination_days': 8,
            'spacing_cm': 30,
            'harvest_window_days': 30,
            'planting_tips': 'Harvest when green for milder flavor or red for maximum heat. Use gloves when handling.',
            'companion_plants': 'Basil, Onions, Spinach'
        },
        {
            'name': 'Habanero',
            'scientific_name': 'Capsicum chinense',
            'category': cat_map['vegetables'],
            'growth_days': 95,
            'image_url': 'https://images.unsplash.com/photo-1563565375-f3fdfdbefa83?auto=format&fit=crop&w=800&q=80',
            'description': 'One of the hottest peppers commonly grown. Lantern-shaped, orange when ripe.',
            'season': 'Summer',
            'difficulty': 'Medium',
            'sunlight': 'Full Sun',
            'watering': 'Moderate',
            'germination_days': 10,
            'spacing_cm': 45,
            'harvest_window_days': 30,
            'planting_tips': 'Extremely hot - use extreme caution when handling. Wear gloves and eye protection.',
            'companion_plants': 'Basil, Onions, Spinach'
        },
        {
            'name': 'Serrano Pepper',
            'scientific_name': 'Capsicum annuum',
            'category': cat_map['vegetables'],
            'growth_days': 75,
            'image_url': 'https://images.unsplash.com/photo-1563565375-f3fdfdbefa83?auto=format&fit=crop&w=800&q=80',
            'description': 'Similar to jalapeño but thinner and hotter. Bright green, ripens to red.',
            'season': 'Summer',
            'difficulty': 'Medium',
            'sunlight': 'Full Sun',
            'watering': 'Moderate',
            'germination_days': 8,
            'spacing_cm': 30,
            'harvest_window_days': 30,
            'planting_tips': 'Popular in Mexican cuisine. Thinner walls than jalapeño, less suitable for stuffing.',
            'companion_plants': 'Basil, Onions, Spinach'
        },
        {
            'name': 'Poblano Pepper',
            'scientific_name': 'Capsicum annuum',
            'category': cat_map['vegetables'],
            'growth_days': 80,
            'image_url': 'https://images.unsplash.com/photo-1563565375-f3fdfdbefa83?auto=format&fit=crop&w=800&q=80',
            'description': 'Heart-shaped pepper that turns reddish-brown when ripe. Mild when green, medium when red.',
            'season': 'Summer',
            'difficulty': 'Medium',
            'sunlight': 'Full Sun',
            'watering': 'Moderate',
            'germination_days': 10,
            'spacing_cm': 45,
            'harvest_window_days': 30,
            'planting_tips': 'Dried form is ancho chile. Essential for chiles rellenos and mole sauce.',
            'companion_plants': 'Basil, Onions, Spinach'
        },
        {
            'name': 'Green Bell Pepper',
            'scientific_name': 'Capsicum annuum',
            'category': cat_map['vegetables'],
            'growth_days': 60,
            'image_url': 'https://images.unsplash.com/photo-1563565375-f3fdfdbefa83?auto=format&fit=crop&w=800&q=80',
            'description': 'Common bell pepper harvested while green. Crisp and mild flavor.',
            'season': 'Summer',
            'difficulty': 'Easy',
            'sunlight': 'Full Sun',
            'watering': 'Moderate',
            'germination_days': 10,
            'spacing_cm': 45,
            'harvest_window_days': 30,
            'planting_tips': 'Harvest when firm and glossy green. Continue picking to encourage more fruit.',
            'companion_plants': 'Basil, Onions, Spinach'
        },
        {
            'name': 'Red Bell Pepper',
            'scientific_name': 'Capsicum annuum',
            'category': cat_map['vegetables'],
            'growth_days': 80,
            'image_url': 'https://images.unsplash.com/photo-1563565375-f3fdfdbefa83?auto=format&fit=crop&w=800&q=80',
            'description': 'Sweet bell pepper left to ripen to red. Higher vitamin C content than green.',
            'season': 'Summer',
            'difficulty': 'Easy',
            'sunlight': 'Full Sun',
            'watering': 'Moderate',
            'germination_days': 10,
            'spacing_cm': 45,
            'harvest_window_days': 30,
            'planting_tips': 'Leave on plant longer for sweeter flavor. Great for roasting and salads.',
            'companion_plants': 'Basil, Onions, Spinach'
        },
        {
            'name': 'Yellow Bell Pepper',
            'scientific_name': 'Capsicum annuum',
            'category': cat_map['vegetables'],
            'growth_days': 75,
            'image_url': 'https://images.unsplash.com/photo-1563565375-f3fdfdbefa83?auto=format&fit=crop&w=800&q=80',
            'description': 'Sweet bell pepper that ripens to sunny yellow. Mild, fruity flavor.',
            'season': 'Summer',
            'difficulty': 'Easy',
            'sunlight': 'Full Sun',
            'watering': 'Moderate',
            'germination_days': 10,
            'spacing_cm': 45,
            'harvest_window_days': 30,
            'planting_tips': 'Adds color to salads and stir-fries. Harvest when firm and yellow.',
            'companion_plants': 'Basil, Onions, Spinach'
        },
        {
            'name': 'Orange Bell Pepper',
            'scientific_name': 'Capsicum annuum',
            'category': cat_map['vegetables'],
            'growth_days': 75,
            'image_url': 'https://images.unsplash.com/photo-1563565375-f3fdfdbefa83?auto=format&fit=crop&w=800&q=80',
            'description': 'Sweet bell pepper that ripens to vibrant orange. Crisp and tangy-sweet flavor.',
            'season': 'Summer',
            'difficulty': 'Easy',
            'sunlight': 'Full Sun',
            'watering': 'Moderate',
            'germination_days': 10,
            'spacing_cm': 45,
            'harvest_window_days': 30,
            'planting_tips': 'Great for stuffing or raw in salads. Excellent source of vitamin A.',
            'companion_plants': 'Basil, Onions, Spinach'
        },
        {
            'name': 'Purple Bell Pepper',
            'scientific_name': 'Capsicum annuum',
            'category': cat_map['vegetables'],
            'growth_days': 80,
            'image_url': 'https://images.unsplash.com/photo-1563565375-f3fdfdbefa83?auto=format&fit=crop&w=800&q=80',
            'description': 'Unique purple bell pepper that turns green when cooked. Striking color for salads.',
            'season': 'Summer',
            'difficulty': 'Medium',
            'sunlight': 'Full Sun',
            'watering': 'Moderate',
            'germination_days': 12,
            'spacing_cm': 45,
            'harvest_window_days': 30,
            'planting_tips': 'Best color when harvested young. Adds visual appeal to vegetable trays.',
            'companion_plants': 'Basil, Onions, Spinach'
        },
        {
            'name': 'Watermelon',
            'scientific_name': 'Citrullus lanatus',
            'category': cat_map['fruits-berries'],
            'growth_days': 85,
            'image_url': 'https://images.unsplash.com/photo-1587049352846-4a222e784d38?auto=format&fit=crop&w=800&q=80',
            'description': 'Classic summer fruit with sweet red flesh and black seeds. Perfect for hot days.',
            'season': 'Summer',
            'difficulty': 'Medium',
            'sunlight': 'Full Sun',
            'watering': 'High',
            'germination_days': 8,
            'spacing_cm': 90,
            'harvest_window_days': 15,
            'planting_tips': 'Look for yellow belly and dry tendril when checking ripeness. Keep soil moist.',
            'companion_plants': 'Corn, Radishes, Marigolds'
        },
        {
            'name': 'Seedless Watermelon',
            'scientific_name': 'Citrullus lanatus',
            'category': cat_map['fruits-berries'],
            'growth_days': 85,
            'image_url': 'https://images.unsplash.com/photo-1587049352846-4a222e784d38?auto=format&fit=crop&w=800&q=80',
            'description': 'Popular watermelon variety with sweet red flesh and tiny, edible white seeds.',
            'season': 'Summer',
            'difficulty': 'Medium',
            'sunlight': 'Full Sun',
            'watering': 'High',
            'germination_days': 8,
            'spacing_cm': 90,
            'harvest_window_days': 15,
            'planting_tips': 'Needs pollinator plant nearby. Same growing requirements as seeded watermelon.',
            'companion_plants': 'Corn, Radishes, Marigolds'
        },
        {
            'name': 'Honeydew Melon',
            'scientific_name': 'Cucumis melo var. inodorus',
            'category': cat_map['fruits-berries'],
            'growth_days': 90,
            'image_url': 'https://images.unsplash.com/photo-1585547678975-5d4b4b4d8b66?auto=format&fit=crop&w=800&q=80',
            'description': 'Smooth, pale green rind with sweet light green flesh. Mild and refreshing flavor.',
            'season': 'Summer',
            'difficulty': 'Medium',
            'sunlight': 'Full Sun',
            'watering': 'High',
            'germination_days': 7,
            'spacing_cm': 90,
            'harvest_window_days': 15,
            'planting_tips': 'Rind changes from green to creamy yellow when ripe. Cut from vine when ready.',
            'companion_plants': 'Corn, Marigold, Nasturtium, Radishes'
        },
        {
            'name': 'Chives',
            'scientific_name': 'Allium schoenoprasum',
            'category': cat_map['herbs-aromatics'],
            'growth_days': 80,
            'image_url': 'https://images.unsplash.com/photo-1596483361280-38b3b3b54a12?auto=format&fit=crop&w=800&q=80',
            'description': 'Mild onion-flavored herb with hollow green leaves. Edible flowers attract pollinators.',
            'season': 'Spring/Summer/Fall',
            'difficulty': 'Easy',
            'sunlight': 'Full Sun/Partial Shade',
            'watering': 'Moderate',
            'germination_days': 10,
            'spacing_cm': 15,
            'harvest_window_days': 120,
            'planting_tips': 'Cut leaves as needed. Plants form attractive clumps that return yearly.',
            'companion_plants': 'Carrots, Tomatoes, Roses'
        },
        {
            'name': 'Leeks',
            'scientific_name': 'Allium ampeloprasum var. porrum',
            'category': cat_map['vegetables'],
            'growth_days': 120,
            'image_url': 'https://images.unsplash.com/photo-1596483361280-38b3b3b54a12?auto=format&fit=crop&w=800&q=80',
            'description': 'Mild, sweet onion relative with thick white stalks. Essential for soups and stews.',
            'season': 'Spring/Fall',
            'difficulty': 'Medium',
            'sunlight': 'Full Sun',
            'watering': 'Moderate',
            'germination_days': 10,
            'spacing_cm': 15,
            'harvest_window_days': 30,
            'planting_tips': 'Blanch by hilling soil around stems. Harvest when stalks are 1 inch thick.',
            'companion_plants': 'Carrots, Celery, Onions'
        },
        {
            'name': 'Shallots',
            'scientific_name': 'Allium cepa var. aggregatum',
            'category': cat_map['vegetables'],
            'growth_days': 90,
            'image_url': 'https://images.unsplash.com/photo-1596483361280-38b3b3b54a12?auto=format&fit=crop&w=800&q=80',
            'description': 'Mild, sweet onions that grow in clusters. Preferred by chefs for delicate flavor.',
            'season': 'Spring/Fall',
            'difficulty': 'Medium',
            'sunlight': 'Full Sun',
            'watering': 'Moderate',
            'germination_days': 10,
            'spacing_cm': 15,
            'harvest_window_days': 30,
            'planting_tips': 'Plant bulbs pointy end up. Harvest when tops yellow and fall over.',
            'companion_plants': 'Carrots, Lettuce, Tomatoes'
        },
        {
            'name': 'Scallions (Green Onions)',
            'scientific_name': 'Allium fistulosum',
            'category': cat_map['vegetables'],
            'growth_days': 60,
            'image_url': 'https://images.unsplash.com/photo-1596483361280-38b3b3b54a12?auto=format&fit=crop&w=800&q=80',
            'description': 'Also called bunching onions. Non-bulbing variety grown for green tops and small white base.',
            'season': 'Spring/Summer/Fall',
            'difficulty': 'Easy',
            'sunlight': 'Full Sun',
            'watering': 'Moderate',
            'germination_days': 7,
            'spacing_cm': 5,
            'harvest_window_days': 60,
            'planting_tips': 'Cut greens as needed. Will regrow from base for multiple harvests.',
            'companion_plants': 'Carrots, Lettuce, Tomatoes'
        },
        {
            'name': 'Amaranth',
            'scientific_name': 'Amaranthus caudatus',
            'category': cat_map['vegetables'],
            'growth_days': 90,
            'image_url': 'https://images.unsplash.com/photo-1596483361280-38b3b3b54a12?auto=format&fit=crop&w=800&q=80',
            'description': 'Ancient grain with edible leaves and seeds. Beautiful red tassels in late summer.',
            'season': 'Summer',
            'difficulty': 'Medium',
            'sunlight': 'Full Sun',
            'watering': 'Moderate',
            'germination_days': 5,
            'spacing_cm': 30,
            'harvest_window_days': 30,
            'planting_tips': 'Harvest leaves young for salads or let mature for grain. Drought-tolerant.',
            'companion_plants': 'Corn, Eggplant, Peppers'
        },
        {
            'name': 'Asparagus',
            'scientific_name': 'Asparagus officinalis',
            'category': cat_map['vegetables'],
            'growth_days': 730,
            'image_url': 'https://images.unsplash.com/photo-1596483361280-38b3b3b54a12?auto=format&fit=crop&w=800&q=80',
            'description': 'Perennial vegetable producing tender spears in spring. Plant once, harvest for years.',
            'season': 'Spring',
            'difficulty': 'Medium',
            'sunlight': 'Full Sun',
            'watering': 'Moderate',
            'germination_days': 21,
            'spacing_cm': 45,
            'harvest_window_days': 60,
            'planting_tips': 'Wait 2 years before harvesting. Cut spears when 6-8 inches tall.',
            'companion_plants': 'Tomatoes, Parsley, Basil'
        },
        {
            'name': 'Rhubarb',
            'scientific_name': 'Rheum rhabarbarum',
            'category': cat_map['vegetables'],
            'growth_days': 730,
            'image_url': 'https://images.unsplash.com/photo-1596483361280-38b3b3b54a12?auto=format&fit=crop&w=800&q=80',
            'description': 'Perennial vegetable with tart red stalks. Leaves are toxic - only eat stalks.',
            'season': 'Spring',
            'difficulty': 'Medium',
            'sunlight': 'Full Sun/Partial Shade',
            'watering': 'Moderate',
            'germination_days': 7,
            'spacing_cm': 60,
            'harvest_window_days': 365,
            'planting_tips': 'Wait 1 year before harvesting. Only stalks are edible - leaves poisonous.',
            'companion_plants': 'Beans, Cabbage, Kale'
        },
        {
            'name': 'Artichoke',
            'scientific_name': 'Cynara scolymus',
            'category': cat_map['vegetables'],
            'growth_days': 150,
            'image_url': 'https://images.unsplash.com/photo-1596483361280-38b3b3b54a12?auto=format&fit=crop&w=800&q=80',
            'description': 'Thistle-like vegetable grown for edible flower buds. Perennial in warm climates.',
            'season': 'Spring',
            'difficulty': 'Medium',
            'sunlight': 'Full Sun',
            'watering': 'Moderate',
            'germination_days': 10,
            'spacing_cm': 120,
            'harvest_window_days': 30,
            'planting_tips': 'Harvest buds before they open. Cut stem 1-2 inches below bud.',
            'companion_plants': 'Peas, Cabbage, Tarragon'
        },
        {
            'name': 'Brussels Sprouts',
            'scientific_name': 'Brassica oleracea var. gemmifera',
            'category': cat_map['vegetables'],
            'growth_days': 300,
            'image_url': 'https://images.unsplash.com/photo-1596483361280-38b3b3b54a12?auto=format&fit=crop&w=800&q=80',
            'description': 'Mini cabbage-like buds that grow along a tall stem. Sweet after frost.',
            'season': 'Autumn/Winter',
            'difficulty': 'Medium',
            'sunlight': 'Full Sun',
            'watering': 'Moderate',
            'germination_days': 10,
            'spacing_cm': 60,
            'harvest_window_days': 60,
            'planting_tips': 'Start indoors for transplant. Harvest from bottom up as sprouts mature.',
            'companion_plants': 'Beets, Celery, Onions'
        },
        {
            'name': 'Celery',
            'scientific_name': 'Apium graveolens var. dulce',
            'category': cat_map['vegetables'],
            'growth_days': 140,
            'image_url': 'https://images.unsplash.com/photo-1596483361280-38b3b3b54a12?auto=format&fit=crop&w=800&q=80',
            'description': 'Crisp, aromatic stalks essential for soups, stews, and salads.',
            'season': 'Spring/Fall',
            'difficulty': 'Medium',
            'sunlight': 'Full Sun',
            'watering': 'High',
            'germination_days': 21,
            'spacing_cm': 25,
            'harvest_window_days': 60,
            'planting_tips': 'Needs constant moisture and rich soil. Blanch stalks for tender flavor.',
            'companion_plants': 'Beans, Cabbage, Leeks, Tomatoes'
        },
        {
            'name': 'Fennel',
            'scientific_name': 'Foeniculum vulgare var. azoricum',
            'category': cat_map['vegetables'],
            'growth_days': 90,
            'image_url': 'https://images.unsplash.com/photo-1596483361280-38b3b3b54a12?auto=format&fit=crop&w=800&q=80',
            'description': 'Licorice-flavored bulb with feathery leaves. Edible raw or cooked.',
            'season': 'Spring/Fall',
            'difficulty': 'Medium',
            'sunlight': 'Full Sun',
            'watering': 'Moderate',
            'germination_days': 10,
            'spacing_cm': 30,
            'harvest_window_days': 30,
            'planting_tips': 'Harvest bulbs when tennis ball size. Fronds useful as herb.',
            'companion_plants': 'None - inhibits some plants'
        },
        {
            'name': 'Kohlrabi',
            'scientific_name': 'Brassica oleracea var. gongylodes',
            'category': cat_map['vegetables'],
            'growth_days': 60,
            'image_url': 'https://images.unsplash.com/photo-1596483361280-38b3b3b54a12?auto=format&fit=crop&w=800&q=80',
            'description': 'Stem vegetable with turnip-like flavor. Grows above ground as swollen stem.',
            'season': 'Spring/Summer',
            'difficulty': 'Easy',
            'sunlight': 'Full Sun',
            'watering': 'Moderate',
            'germination_days': 10,
            'spacing_cm': 20,
            'harvest_window_days': 30,
            'planting_tips': 'Harvest when stem is 2-3 inches diameter. Both purple and white varieties available.',
            'companion_plants': 'Beets, Celery, Onions'
        }
    ]

    for crop_data in crops_data:
        c, created = Crop.objects.update_or_create(
            name=crop_data['name'],
            defaults=crop_data
        )
        if created:
            print(f'Created crop: {c.name} ({c.growth_days} days)')

    # 4. Create sample schedule for gardener user (only if demo accounts exist)
    if CREATE_DEMO_ACCOUNTS and gardener_user:
        UserCropSchedule.objects.filter(user=gardener_user).delete()
        today = date.today()

        sample_schedules = [
            {
                'crop': Crop.objects.get(name='French Breakfast Radish'),
                'planted_date': today - timedelta(days=15),
                'quantity': 20,
                'plot_location': 'Raised Bed 1 - East Side',
                'status': 'growing',
                'notes': 'Sprouted in 3 days! Looking lush and healthy.'
            },
            {
                'crop': Crop.objects.get(name='San Marzano Tomato'),
                'planted_date': today - timedelta(days=40),
                'quantity': 4,
                'plot_location': 'Main Garden Row 3',
                'status': 'growing',
                'notes': 'Staked and pruned lower suckers. First yellow blossoms opening.'
            },
            {
                'crop': Crop.objects.get(name='Genovese Basil'),
                'planted_date': today - timedelta(days=38),
                'quantity': 6,
                'plot_location': 'Herb Spiral - Top tier',
                'status': 'ready',
                'notes': 'Ready for the first big harvest for basil pesto!'
            },
            {
                'crop': Crop.objects.get(name='Sweet Rainbow Carrots'),
                'planted_date': today + timedelta(days=5),
                'quantity': 30,
                'plot_location': 'Raised Bed 2',
                'status': 'planned',
                'notes': 'Preparing fluffy sandy bed this upcoming weekend.'
            }
        ]

        for item in sample_schedules:
            est_harvest = item['planted_date'] + timedelta(days=item['crop'].growth_days)
            UserCropSchedule.objects.create(
                user=gardener_user,
                crop=item['crop'],
                planted_date=item['planted_date'],
                estimated_harvest_date=est_harvest,
                quantity=item['quantity'],
                plot_location=item['plot_location'],
                status=item['status'],
                notes=item['notes']
            )
        print('Sample schedules created for gardener user!')
    elif not CREATE_DEMO_ACCOUNTS:
        print('Sample schedule creation skipped (demo accounts disabled)')

    print('Database seed completed successfully!')

if __name__ == '__main__':
    seed()
