# Generated by Django 5.2.17 on 2026-09-15 00:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('icon', models.CharField(default='Leaf', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('scientific_name', models.CharField(blank=True, default='', max_length=150)),
                ('growth_days', models.PositiveIntegerField(help_text='Total days from planting to harvest')),
                ('image_url', models.URLField(blank=True, default='', max_length=500)),
                ('description', models.TextField()),
                ('season', models.CharField(choices=[('Spring', 'Spring'), ('Summer', 'Summer'), ('Autumn', 'Autumn'), ('Winter', 'Winter'), ('All Season', 'All Season')], default='Spring', max_length=20)),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Easy', max_length=20)),
                ('sunlight', models.CharField(choices=[('Full Sun', 'Full Sun (6+ hrs)'), ('Partial Shade', 'Partial Shade (3-6 hrs)'), ('Full Shade', 'Full Shade')], default='Full Sun', max_length=30)),
                ('watering', models.CharField(choices=[('Low', 'Low'), ('Moderate', 'Moderate'), ('High', 'High')], default='Moderate', max_length=20)),
                ('germination_days', models.PositiveIntegerField(default=7, help_text='Days for seeds to sprout')),
                ('spacing_cm', models.PositiveIntegerField(default=30, help_text='Spacing between plants in cm')),
                ('harvest_window_days', models.PositiveIntegerField(default=14, help_text='Duration in days harvest remains viable')),
                ('planting_tips', models.TextField(blank=True, default='')),
                ('companion_plants', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crops', to='crops.category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserCropSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planted_date', models.DateField(help_text='Date planted or planned to be planted')),
                ('estimated_harvest_date', models.DateField(blank=True, help_text='Calculated based on crop growth days', null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('plot_location', models.CharField(default='Plot A', max_length=100)),
                ('notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('growing', 'Growing'), ('ready', 'Ready to Harvest'), ('harvested', 'Harvested')], default='planned', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='crops.crop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['planted_date', '-created_at'],
            },
        ),
    ]
